export type LanguageCode = 'en' | 'th' | 'ru' | 'zh' | 'ja' | 'es' | 'hi' | 'fr'

export const languageOptions: { code: LanguageCode; label: string; short: string }[] = [
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'th', label: 'ไทย', short: 'TH' },
  { code: 'ru', label: 'Русский', short: 'RU' },
  { code: 'zh', label: '中文', short: '中文' },
  { code: 'ja', label: '日本語', short: '日本' },
  { code: 'es', label: 'Español', short: 'ES' },
  { code: 'hi', label: 'हिन्दी', short: 'हिं' },
  { code: 'fr', label: 'Français', short: 'FR' },
]

const en = {
  language: 'Language', appTitle: 'LumaCut — Video Editor', untitledProject: 'Untitled project', export: 'Export', exporting: 'Exporting…',
  media: 'Media', audio: 'Audio', text: 'Text', stickers: 'Stickers', effects: 'Effects', captions: 'Captions',
  myLibrary: 'My library', importMedia: 'Import media', inProject: 'In project', yourFile: 'Your file', sample: 'Sample',
  detachedDone: 'Audio detached — edit independently', detachAudio: 'Detach audio from video', dropVideo: 'Drag and drop a video here',
  addText: 'Add text', quickStyles: 'Quick styles', heading: 'Heading', captionPreset: 'Caption', textLayers: 'Text layers',
  importAudio: 'Import audio', audioInProject: 'Audio in project', readyTimeline: 'Ready to edit in timeline', clickChooseAudio: 'Click to choose an audio file',
  audioTip: 'Select an audio clip below, then drag to move it or use scissors to split it', recordAudio: 'Record audio', stopRecording: 'Stop recording',
  captionPlaceholder: 'Type a caption…', addAtPlayhead: 'Add at playhead', importSrt: 'Import SRT', captionsInProject: 'Captions in project', noCaptions: 'No captions yet',
  searchStickers: 'Search stickers…', noStickers: 'No stickers found', stickerCredit: 'Free stickers by OpenMoji · CC BY-SA 4.0',
  fit: 'Fit', animation: 'Animation', format: 'Format', font: 'Font', size: 'Size', rotate: 'Rotate', opacity: 'Opacity', position: 'Position',
  horizontal: 'Horizontal', vertical: 'Vertical', displayTime: 'Display time', start: 'Start', duration: 'Duration', seconds: 'seconds',
  deleteSticker: 'Delete sticker', editCaption: 'Edit caption', deleteCaption: 'Delete caption', style: 'Style', editText: 'Edit text', deleteText: 'Delete text',
  video: 'Video', adjust: 'Adjust', basic: 'Basic', stabilize: 'Stabilize', speed: 'Speed', volume: 'Volume', colorAdjust: 'Color adjustment',
  brightness: 'Brightness', contrast: 'Contrast', saturation: 'Saturation', reset: 'Reset adjustments',
  mainVideo: 'Main video', trackVideo: 'Video', trackText: 'Text', trackSticker: 'Sticker', trackCaption: 'Caption', trackAudio: 'Audio',
  splitClip: 'Split clip (Ctrl+B)', deleteItem: 'Delete (Delete)', openStickers: 'Open sticker library', zoomOut: 'Zoom out timeline',
  zoomHelp: 'Drag left to zoom out, right to zoom in', zoomPercent: 'Timeline zoom percentage', zoomIn: 'Zoom in timeline',
  trimStart: 'Drag to trim the start', resizeDuration: 'Drag to change duration', addTrack: 'Add {track} track', deleteTrack: 'Delete {track} track',
  dropTitle: 'Drop video here', dropDescription: 'The file will be added to your project',
  film: 'Film', lightLeak: 'Light leak', blur: 'Blur', grain: 'Grain', soft: 'Soft',
  animationNone: 'None', fadeIn: 'Fade in', fadeOut: 'Fade out', zoomInAnimation: 'Zoom in', slideUp: 'Slide up', slideLeft: 'Slide left', animationDuration: 'Animation duration', animationHint: 'Play or move the playhead to preview the animation.', selectClipForAnimation: 'Select a video clip to add animation',
  transition: 'Transition', transitionNone: 'None', crossfade: 'Crossfade', fadeBlack: 'Fade through black', transitionSlideLeft: 'Slide left', transitionSlideUp: 'Slide up', transitionZoom: 'Zoom blend', transitionDuration: 'Transition duration', transitionHint: 'The transition plays at the start of this clip. Play or move the playhead to preview it.', transitionNeedsClip: 'Place this clip directly after another clip to add a transition.', selectClipForTransition: 'Select a video clip to add a transition',
  noAudioFile: 'No audio file', clip: 'Clip', zoomChanged: 'Timeline zoom {zoom}%', splitHint: 'Move the playhead inside the {item} before splitting', splitDone: '{item} split',
  selectVideoFile: 'Please select a video file', importedVideo: 'Video imported', importVideoFirst: 'Import a video first', alreadyDetached: 'Audio is already detached', sourceAudio: '{name} — audio from video', audioSuffix: '{name} (audio)', detachedAudio: 'Audio detached from video',
  selectAudioFile: 'Please select an audio file', importedAudio: 'Audio added to the timeline', recordingUnsupported: 'Audio recording is not supported on this device', noRecordingData: 'No microphone audio was captured', recordingLabel: 'Recording {time}', recordedAudio: 'Recorded {duration} seconds of audio', recordingError: 'An error occurred while recording', recordingNow: 'Recording… click again to stop', microphoneDenied: 'Microphone unavailable. Please allow microphone access',
  deleted: '{item} deleted', newText: 'New text', added: '{item} added', invalidSrt: 'No valid captions were found in the SRT file', srtImported: 'Imported {count} captions', srtReadFailed: 'Could not read the caption file', moved: '{item} moved', clipStartAdjusted: 'Clip start adjusted', clipDurationAdjusted: 'Clip duration adjusted', minimumTrack: 'At least one track of each type is required',
  exportFirst: 'Import a video before exporting', preparingVideo: 'Preparing video…', exportSuccess: 'Video exported successfully', exportFailed: 'Export failed. Try a shorter video',
}

type MessageKey = keyof typeof en
type Dictionary = Partial<Record<MessageKey, string>>

const th: Dictionary = {
  language: 'ภาษา', appTitle: 'LumaCut — โปรแกรมตัดต่อวิดีโอ', untitledProject: 'โปรเจกต์ไม่มีชื่อ', export: 'ส่งออก', exporting: 'กำลังส่งออก…',
  media: 'สื่อ', audio: 'เสียง', text: 'ข้อความ', stickers: 'สติกเกอร์', effects: 'เอฟเฟกต์', captions: 'คำบรรยาย',
  myLibrary: 'คลังของฉัน', importMedia: 'นำเข้าสื่อ', inProject: 'ในโปรเจกต์', yourFile: 'ไฟล์ของคุณ', sample: 'ตัวอย่าง',
  detachedDone: 'แยกเสียงแล้ว — แก้ไขได้อิสระ', detachAudio: 'แยกเสียงออกจากวิดีโอ', dropVideo: 'ลากไฟล์วิดีโอมาวางได้เลย',
  addText: 'เพิ่มข้อความ', quickStyles: 'รูปแบบด่วน', heading: 'หัวเรื่อง', captionPreset: 'คำบรรยาย', textLayers: 'เลเยอร์ข้อความ',
  importAudio: 'นำเข้าเสียง', audioInProject: 'เสียงในโปรเจกต์', readyTimeline: 'พร้อมแก้ไขใน Timeline', clickChooseAudio: 'คลิกเพื่อเลือกไฟล์เสียง',
  audioTip: 'เลือกคลิปเสียงด้านล่าง แล้วลากเพื่อย้ายตำแหน่ง หรือกดกรรไกรเพื่อแบ่ง', recordAudio: 'บันทึกเสียง', stopRecording: 'หยุดบันทึก',
  captionPlaceholder: 'พิมพ์คำบรรยาย…', addAtPlayhead: 'เพิ่มที่ตำแหน่งหัวอ่าน', importSrt: 'นำเข้าไฟล์ SRT', captionsInProject: 'คำบรรยายในโปรเจกต์', noCaptions: 'ยังไม่มีคำบรรยาย',
  searchStickers: 'ค้นหาสติกเกอร์…', noStickers: 'ไม่พบสติกเกอร์', stickerCredit: 'สติกเกอร์ฟรีโดย OpenMoji · CC BY-SA 4.0',
  fit: 'พอดี', animation: 'แอนิเมชัน', format: 'รูปแบบ', font: 'ฟอนต์', size: 'ขนาด', rotate: 'หมุน', opacity: 'ความทึบ', position: 'ตำแหน่ง',
  horizontal: 'แนวนอน', vertical: 'แนวตั้ง', displayTime: 'เวลาแสดงผล', start: 'เริ่ม', duration: 'ความยาว', seconds: 'วินาที',
  deleteSticker: 'ลบสติกเกอร์', editCaption: 'แก้ไขคำบรรยาย', deleteCaption: 'ลบคำบรรยาย', style: 'สไตล์', editText: 'แก้ไขข้อความ', deleteText: 'ลบข้อความ',
  video: 'วิดีโอ', adjust: 'ปรับแต่ง', basic: 'พื้นฐาน', stabilize: 'ลดการสั่น', speed: 'ความเร็ว', volume: 'ระดับเสียง', colorAdjust: 'ปรับสี',
  brightness: 'ความสว่าง', contrast: 'คอนทราสต์', saturation: 'ความอิ่มสี', reset: 'รีเซ็ตการปรับแต่ง',
  mainVideo: 'วิดีโอหลัก', trackVideo: 'วิดีโอ', trackText: 'ข้อความ', trackSticker: 'สติกเกอร์', trackCaption: 'คำบรรยาย', trackAudio: 'เสียง',
  splitClip: 'แบ่งคลิป (Ctrl+B)', deleteItem: 'ลบ (Delete)', openStickers: 'เปิดคลังสติกเกอร์', zoomOut: 'ย่อ Timeline',
  zoomHelp: 'ลากซ้ายเพื่อย่อ ลากขวาเพื่อขยาย', zoomPercent: 'เปอร์เซ็นต์ซูม Timeline', zoomIn: 'ขยาย Timeline',
  trimStart: 'ลากเพื่อปรับจุดเริ่มต้น', resizeDuration: 'ลากเพื่อปรับความยาว', addTrack: 'เพิ่มแทร็ก{track}', deleteTrack: 'ลบแทร็ก {track}',
  dropTitle: 'วางวิดีโอที่นี่', dropDescription: 'ไฟล์จะถูกเพิ่มลงในโปรเจกต์', film: 'ฟิล์ม', lightLeak: 'แสงรั่ว', blur: 'เบลอ', grain: 'เกรน', soft: 'ซอฟต์',
  animationNone: 'ไม่มี', fadeIn: 'ค่อย ๆ ปรากฏ', fadeOut: 'ค่อย ๆ จาง', zoomInAnimation: 'ซูมเข้า', slideUp: 'เลื่อนขึ้น', slideLeft: 'เลื่อนไปซ้าย', animationDuration: 'ระยะเวลาแอนิเมชัน', animationHint: 'กดเล่นหรือเลื่อนหัวอ่านเพื่อดูตัวอย่างแอนิเมชัน', selectClipForAnimation: 'เลือกคลิปวิดีโอเพื่อเพิ่มแอนิเมชัน',
  transition: 'ทรานซิชัน', transitionNone: 'ไม่มี', crossfade: 'ภาพซ้อนจาง', fadeBlack: 'จางผ่านสีดำ', transitionSlideLeft: 'เลื่อนไปซ้าย', transitionSlideUp: 'เลื่อนขึ้น', transitionZoom: 'ซูมผสาน', transitionDuration: 'ระยะเวลาทรานซิชัน', transitionHint: 'ทรานซิชันจะแสดงตอนเริ่มคลิปนี้ กดเล่นหรือเลื่อนหัวอ่านเพื่อดูตัวอย่าง', transitionNeedsClip: 'วางคลิปนี้ต่อจากคลิปก่อนหน้าโดยตรงเพื่อเพิ่มทรานซิชัน', selectClipForTransition: 'เลือกคลิปวิดีโอเพื่อเพิ่มทรานซิชัน',
  noAudioFile: 'ยังไม่มีไฟล์เสียง', clip: 'คลิป', zoomChanged: 'ซูม Timeline {zoom}%', splitHint: 'เลื่อนหัวอ่านให้อยู่กลาง{item}ก่อนแบ่ง', splitDone: 'แบ่ง{item}แล้ว', selectVideoFile: 'กรุณาเลือกไฟล์วิดีโอ', importedVideo: 'นำเข้าวิดีโอแล้ว', importVideoFirst: 'นำเข้าวิดีโอก่อน', alreadyDetached: 'แยกเสียงจากวิดีโอแล้ว', sourceAudio: '{name} — เสียงจากวิดีโอ', audioSuffix: '{name} (เสียง)', detachedAudio: 'แยกเสียงออกจากวิดีโอแล้ว', selectAudioFile: 'กรุณาเลือกไฟล์เสียง', importedAudio: 'เพิ่มไฟล์เสียงลง Timeline แล้ว', recordingUnsupported: 'อุปกรณ์นี้ไม่รองรับการบันทึกเสียง', noRecordingData: 'ไม่พบข้อมูลเสียงจากไมโครโฟน', recordingLabel: 'เสียงบันทึก {time}', recordedAudio: 'บันทึกเสียง {duration} วินาทีแล้ว', recordingError: 'เกิดข้อผิดพลาดขณะบันทึกเสียง', recordingNow: 'กำลังบันทึกเสียง… กดอีกครั้งเพื่อหยุด', microphoneDenied: 'ไม่สามารถใช้ไมโครโฟนได้ กรุณาอนุญาตสิทธิ์ไมโครโฟน', deleted: 'ลบ{item}แล้ว', newText: 'ข้อความใหม่', added: 'เพิ่ม{item}แล้ว', invalidSrt: 'ไม่พบคำบรรยายที่ถูกต้องในไฟล์ SRT', srtImported: 'นำเข้าคำบรรยาย {count} รายการแล้ว', srtReadFailed: 'ไม่สามารถอ่านไฟล์คำบรรยายได้', moved: 'ย้ายตำแหน่ง{item}แล้ว', clipStartAdjusted: 'ปรับจุดเริ่มต้นคลิปแล้ว', clipDurationAdjusted: 'ปรับความยาวคลิปแล้ว', minimumTrack: 'ต้องเหลืออย่างน้อย 1 แทร็กต่อชนิด', exportFirst: 'นำเข้าวิดีโอก่อนส่งออก', preparingVideo: 'กำลังเตรียมวิดีโอ…', exportSuccess: 'ส่งออกวิดีโอสำเร็จ', exportFailed: 'ส่งออกไม่สำเร็จ ลองใช้วิดีโอที่สั้นลง',
}

const ru: Dictionary = {
  animationNone: 'Нет', fadeIn: 'Появление', fadeOut: 'Исчезновение', zoomInAnimation: 'Приближение', slideUp: 'Снизу вверх', slideLeft: 'Сдвиг влево', animationDuration: 'Длительность анимации', animationHint: 'Запустите воспроизведение или переместите курсор для просмотра анимации.', selectClipForAnimation: 'Выберите видеоклип для анимации',
  transition: 'Переход', transitionNone: 'Нет', crossfade: 'Перекрёстное затухание', fadeBlack: 'Через чёрный', transitionSlideLeft: 'Сдвиг влево', transitionSlideUp: 'Сдвиг вверх', transitionZoom: 'Зум-переход', transitionDuration: 'Длительность перехода', transitionHint: 'Переход воспроизводится в начале клипа.', transitionNeedsClip: 'Поместите клип сразу после другого клипа.', selectClipForTransition: 'Выберите видеоклип для перехода',
  language: 'Язык', appTitle: 'LumaCut — Видеоредактор', untitledProject: 'Проект без названия', export: 'Экспорт', exporting: 'Экспорт…', media: 'Медиа', audio: 'Аудио', text: 'Текст', stickers: 'Стикеры', effects: 'Эффекты', captions: 'Субтитры',
  myLibrary: 'Моя библиотека', importMedia: 'Импорт медиа', inProject: 'В проекте', yourFile: 'Ваш файл', sample: 'Пример', detachedDone: 'Аудио отделено — редактируется отдельно', detachAudio: 'Отделить аудио от видео', dropVideo: 'Перетащите видео сюда',
  addText: 'Добавить текст', quickStyles: 'Быстрые стили', heading: 'Заголовок', captionPreset: 'Подпись', textLayers: 'Слои текста', importAudio: 'Импорт аудио', audioInProject: 'Аудио в проекте', readyTimeline: 'Готово к монтажу', clickChooseAudio: 'Нажмите, чтобы выбрать аудио', audioTip: 'Выберите аудиоклип, перетащите его или разделите ножницами', recordAudio: 'Записать аудио', stopRecording: 'Остановить запись',
  captionPlaceholder: 'Введите субтитр…', addAtPlayhead: 'Добавить в позиции курсора', importSrt: 'Импорт SRT', captionsInProject: 'Субтитры проекта', noCaptions: 'Субтитров пока нет', searchStickers: 'Поиск стикеров…', noStickers: 'Стикеры не найдены', stickerCredit: 'Бесплатные стикеры OpenMoji · CC BY-SA 4.0',
  fit: 'Вписать', animation: 'Анимация', format: 'Формат', font: 'Шрифт', size: 'Размер', rotate: 'Поворот', opacity: 'Непрозрачность', position: 'Позиция', horizontal: 'По горизонтали', vertical: 'По вертикали', displayTime: 'Время показа', start: 'Начало', duration: 'Длительность', seconds: 'секунд', deleteSticker: 'Удалить стикер', editCaption: 'Изменить субтитр', deleteCaption: 'Удалить субтитр', style: 'Стиль', editText: 'Изменить текст', deleteText: 'Удалить текст',
  video: 'Видео', adjust: 'Коррекция', basic: 'Основное', stabilize: 'Стабилизация', speed: 'Скорость', volume: 'Громкость', colorAdjust: 'Цветокоррекция', brightness: 'Яркость', contrast: 'Контраст', saturation: 'Насыщенность', reset: 'Сбросить настройки', mainVideo: 'Основное видео', trackVideo: 'Видео', trackText: 'Текст', trackSticker: 'Стикер', trackCaption: 'Субтитры', trackAudio: 'Аудио',
  splitClip: 'Разделить клип (Ctrl+B)', deleteItem: 'Удалить (Delete)', openStickers: 'Открыть стикеры', zoomOut: 'Уменьшить таймлайн', zoomHelp: 'Влево — уменьшить, вправо — увеличить', zoomPercent: 'Масштаб таймлайна', zoomIn: 'Увеличить таймлайн', trimStart: 'Перетащите, чтобы обрезать начало', resizeDuration: 'Перетащите для изменения длины', addTrack: 'Добавить дорожку: {track}', deleteTrack: 'Удалить дорожку: {track}', dropTitle: 'Перетащите видео сюда', dropDescription: 'Файл будет добавлен в проект', film: 'Плёнка', lightLeak: 'Засветка', blur: 'Размытие', grain: 'Зерно', soft: 'Мягкий',
  noAudioFile: 'Нет аудиофайла', clip: 'Клип', zoomChanged: 'Масштаб таймлайна {zoom}%', splitHint: 'Поместите курсор внутрь элемента «{item}» перед разделением', splitDone: '{item}: разделено', selectVideoFile: 'Выберите видеофайл', importedVideo: 'Видео импортировано', importVideoFirst: 'Сначала импортируйте видео', alreadyDetached: 'Аудио уже отделено', sourceAudio: '{name} — аудио из видео', audioSuffix: '{name} (аудио)', detachedAudio: 'Аудио отделено от видео', selectAudioFile: 'Выберите аудиофайл', importedAudio: 'Аудио добавлено на таймлайн', recordingUnsupported: 'Запись звука не поддерживается на этом устройстве', noRecordingData: 'Звук с микрофона не записан', recordingLabel: 'Запись {time}', recordedAudio: 'Записано аудио: {duration} с', recordingError: 'Ошибка во время записи', recordingNow: 'Идёт запись… нажмите ещё раз для остановки', microphoneDenied: 'Микрофон недоступен. Разрешите доступ к микрофону', deleted: '{item}: удалено', newText: 'Новый текст', added: '{item}: добавлено', invalidSrt: 'В файле SRT нет корректных субтитров', srtImported: 'Импортировано субтитров: {count}', srtReadFailed: 'Не удалось прочитать файл субтитров', moved: '{item}: перемещено', clipStartAdjusted: 'Начало клипа изменено', clipDurationAdjusted: 'Длительность клипа изменена', minimumTrack: 'Требуется хотя бы одна дорожка каждого типа', exportFirst: 'Импортируйте видео перед экспортом', preparingVideo: 'Подготовка видео…', exportSuccess: 'Видео успешно экспортировано', exportFailed: 'Ошибка экспорта. Попробуйте более короткое видео',
}

const zh: Dictionary = {
  animationNone: '无', fadeIn: '淡入', fadeOut: '淡出', zoomInAnimation: '放大进入', slideUp: '向上滑入', slideLeft: '向左滑入', animationDuration: '动画时长', animationHint: '播放或移动播放头以预览动画。', selectClipForAnimation: '选择视频片段以添加动画',
  transition: '转场', transitionNone: '无', crossfade: '交叉淡化', fadeBlack: '黑场淡化', transitionSlideLeft: '向左滑动', transitionSlideUp: '向上滑动', transitionZoom: '缩放融合', transitionDuration: '转场时长', transitionHint: '转场将在此片段开始时播放。', transitionNeedsClip: '请将此片段紧接在另一个片段之后。', selectClipForTransition: '选择视频片段以添加转场',
  language: '语言', appTitle: 'LumaCut — 视频编辑器', untitledProject: '未命名项目', export: '导出', exporting: '正在导出…', media: '媒体', audio: '音频', text: '文字', stickers: '贴纸', effects: '特效', captions: '字幕', myLibrary: '我的素材库', importMedia: '导入媒体', inProject: '项目中', yourFile: '你的文件', sample: '示例', detachedDone: '音频已分离 — 可独立编辑', detachAudio: '从视频分离音频', dropVideo: '将视频拖放到这里', addText: '添加文字', quickStyles: '快速样式', heading: '标题', captionPreset: '字幕', textLayers: '文字图层', importAudio: '导入音频', audioInProject: '项目音频', readyTimeline: '可在时间线中编辑', clickChooseAudio: '点击选择音频文件', audioTip: '选择下方音频片段，拖动移动或用剪刀分割', recordAudio: '录制音频', stopRecording: '停止录制', captionPlaceholder: '输入字幕…', addAtPlayhead: '在播放头处添加', importSrt: '导入 SRT', captionsInProject: '项目字幕', noCaptions: '暂无字幕', searchStickers: '搜索贴纸…', noStickers: '未找到贴纸', stickerCredit: 'OpenMoji 免费贴纸 · CC BY-SA 4.0', fit: '适应', animation: '动画', format: '格式', font: '字体', size: '大小', rotate: '旋转', opacity: '不透明度', position: '位置', horizontal: '水平', vertical: '垂直', displayTime: '显示时间', start: '开始', duration: '时长', seconds: '秒', deleteSticker: '删除贴纸', editCaption: '编辑字幕', deleteCaption: '删除字幕', style: '样式', editText: '编辑文字', deleteText: '删除文字', video: '视频', adjust: '调整', basic: '基础', stabilize: '防抖', speed: '速度', volume: '音量', colorAdjust: '颜色调整', brightness: '亮度', contrast: '对比度', saturation: '饱和度', reset: '重置调整', mainVideo: '主视频', trackVideo: '视频', trackText: '文字', trackSticker: '贴纸', trackCaption: '字幕', trackAudio: '音频', splitClip: '分割片段 (Ctrl+B)', deleteItem: '删除 (Delete)', openStickers: '打开贴纸库', zoomOut: '缩小时间线', zoomHelp: '向左拖动缩小，向右拖动放大', zoomPercent: '时间线缩放百分比', zoomIn: '放大时间线', trimStart: '拖动以裁剪开头', resizeDuration: '拖动以更改时长', addTrack: '添加{track}轨道', deleteTrack: '删除{track}轨道', dropTitle: '将视频放到这里', dropDescription: '文件将添加到项目', film: '胶片', lightLeak: '漏光', blur: '模糊', grain: '颗粒', soft: '柔和',
  noAudioFile: '没有音频文件', clip: '片段', zoomChanged: '时间线缩放 {zoom}%', splitHint: '分割前请将播放头移到{item}内部', splitDone: '{item}已分割', selectVideoFile: '请选择视频文件', importedVideo: '视频已导入', importVideoFirst: '请先导入视频', alreadyDetached: '音频已分离', sourceAudio: '{name} — 视频音频', audioSuffix: '{name}（音频）', detachedAudio: '已从视频分离音频', selectAudioFile: '请选择音频文件', importedAudio: '音频已添加到时间线', recordingUnsupported: '此设备不支持录音', noRecordingData: '未捕获到麦克风音频', recordingLabel: '录音 {time}', recordedAudio: '已录制 {duration} 秒音频', recordingError: '录音时发生错误', recordingNow: '正在录音…再次点击停止', microphoneDenied: '麦克风不可用，请允许麦克风权限', deleted: '{item}已删除', newText: '新文字', added: '{item}已添加', invalidSrt: 'SRT 文件中未找到有效字幕', srtImported: '已导入 {count} 条字幕', srtReadFailed: '无法读取字幕文件', moved: '{item}已移动', clipStartAdjusted: '片段起点已调整', clipDurationAdjusted: '片段时长已调整', minimumTrack: '每种类型至少需要一条轨道', exportFirst: '导出前请先导入视频', preparingVideo: '正在准备视频…', exportSuccess: '视频导出成功', exportFailed: '导出失败，请尝试较短的视频',
}

const ja: Dictionary = {
  animationNone: 'なし', fadeIn: 'フェードイン', fadeOut: 'フェードアウト', zoomInAnimation: 'ズームイン', slideUp: '上へスライド', slideLeft: '左へスライド', animationDuration: 'アニメーション時間', animationHint: '再生または再生ヘッドを移動してプレビューします。', selectClipForAnimation: 'アニメーションを追加する動画を選択',
  transition: 'トランジション', transitionNone: 'なし', crossfade: 'クロスフェード', fadeBlack: '黒へフェード', transitionSlideLeft: '左へスライド', transitionSlideUp: '上へスライド', transitionZoom: 'ズームブレンド', transitionDuration: 'トランジション時間', transitionHint: 'このクリップの開始時に再生されます。', transitionNeedsClip: 'このクリップを前のクリップに隣接させてください。', selectClipForTransition: 'トランジションを追加する動画を選択',
  language: '言語', appTitle: 'LumaCut — 動画編集', untitledProject: '無題のプロジェクト', export: '書き出し', exporting: '書き出し中…', media: 'メディア', audio: 'オーディオ', text: 'テキスト', stickers: 'ステッカー', effects: 'エフェクト', captions: '字幕', myLibrary: 'マイライブラリ', importMedia: 'メディアを読み込む', inProject: 'プロジェクト内', yourFile: 'あなたのファイル', sample: 'サンプル', detachedDone: '音声を分離済み — 個別編集可能', detachAudio: '動画から音声を分離', dropVideo: '動画をここにドロップ', addText: 'テキストを追加', quickStyles: 'クイックスタイル', heading: '見出し', captionPreset: 'キャプション', textLayers: 'テキストレイヤー', importAudio: '音声を読み込む', audioInProject: 'プロジェクトの音声', readyTimeline: 'タイムラインで編集できます', clickChooseAudio: 'クリックして音声を選択', audioTip: '下の音声クリップを選び、ドラッグで移動またはハサミで分割します', recordAudio: '音声を録音', stopRecording: '録音を停止', captionPlaceholder: '字幕を入力…', addAtPlayhead: '再生ヘッドに追加', importSrt: 'SRTを読み込む', captionsInProject: 'プロジェクトの字幕', noCaptions: '字幕はまだありません', searchStickers: 'ステッカーを検索…', noStickers: 'ステッカーが見つかりません', stickerCredit: 'OpenMojiの無料ステッカー · CC BY-SA 4.0', fit: 'フィット', animation: 'アニメーション', format: '書式', font: 'フォント', size: 'サイズ', rotate: '回転', opacity: '不透明度', position: '位置', horizontal: '水平', vertical: '垂直', displayTime: '表示時間', start: '開始', duration: '長さ', seconds: '秒', deleteSticker: 'ステッカーを削除', editCaption: '字幕を編集', deleteCaption: '字幕を削除', style: 'スタイル', editText: 'テキストを編集', deleteText: 'テキストを削除', video: '動画', adjust: '調整', basic: '基本', stabilize: '手ぶれ補正', speed: '速度', volume: '音量', colorAdjust: 'カラー調整', brightness: '明るさ', contrast: 'コントラスト', saturation: '彩度', reset: '調整をリセット', mainVideo: 'メイン動画', trackVideo: '動画', trackText: 'テキスト', trackSticker: 'ステッカー', trackCaption: '字幕', trackAudio: '音声', splitClip: 'クリップを分割 (Ctrl+B)', deleteItem: '削除 (Delete)', openStickers: 'ステッカーライブラリを開く', zoomOut: 'タイムラインを縮小', zoomHelp: '左へドラッグで縮小、右で拡大', zoomPercent: 'タイムラインのズーム率', zoomIn: 'タイムラインを拡大', trimStart: 'ドラッグして開始位置をトリミング', resizeDuration: 'ドラッグして長さを変更', addTrack: '{track}トラックを追加', deleteTrack: '{track}トラックを削除', dropTitle: '動画をここにドロップ', dropDescription: 'ファイルをプロジェクトに追加します', film: 'フィルム', lightLeak: '光漏れ', blur: 'ぼかし', grain: 'グレイン', soft: 'ソフト',
  noAudioFile: '音声ファイルなし', clip: 'クリップ', zoomChanged: 'タイムラインのズーム {zoom}%', splitHint: '分割する前に再生ヘッドを{item}内に移動してください', splitDone: '{item}を分割しました', selectVideoFile: '動画ファイルを選択してください', importedVideo: '動画を読み込みました', importVideoFirst: '先に動画を読み込んでください', alreadyDetached: '音声はすでに分離されています', sourceAudio: '{name} — 動画の音声', audioSuffix: '{name}（音声）', detachedAudio: '動画から音声を分離しました', selectAudioFile: '音声ファイルを選択してください', importedAudio: '音声をタイムラインに追加しました', recordingUnsupported: 'このデバイスは録音に対応していません', noRecordingData: 'マイクの音声が記録されませんでした', recordingLabel: '録音 {time}', recordedAudio: '{duration}秒の音声を録音しました', recordingError: '録音中にエラーが発生しました', recordingNow: '録音中…もう一度クリックして停止', microphoneDenied: 'マイクを使用できません。アクセスを許可してください', deleted: '{item}を削除しました', newText: '新しいテキスト', added: '{item}を追加しました', invalidSrt: 'SRTファイルに有効な字幕がありません', srtImported: '字幕を{count}件読み込みました', srtReadFailed: '字幕ファイルを読み込めませんでした', moved: '{item}を移動しました', clipStartAdjusted: 'クリップの開始位置を調整しました', clipDurationAdjusted: 'クリップの長さを調整しました', minimumTrack: '各種類に少なくとも1つのトラックが必要です', exportFirst: '書き出す前に動画を読み込んでください', preparingVideo: '動画を準備中…', exportSuccess: '動画を書き出しました', exportFailed: '書き出しに失敗しました。短い動画でお試しください',
}

const es: Dictionary = {
  animationNone: 'Ninguna', fadeIn: 'Aparecer', fadeOut: 'Desvanecer', zoomInAnimation: 'Acercar', slideUp: 'Deslizar arriba', slideLeft: 'Deslizar a la izquierda', animationDuration: 'Duración de animación', animationHint: 'Reproduce o mueve el cabezal para previsualizar la animación.', selectClipForAnimation: 'Selecciona un clip de vídeo para animarlo',
  transition: 'Transición', transitionNone: 'Ninguna', crossfade: 'Fundido cruzado', fadeBlack: 'Fundido a negro', transitionSlideLeft: 'Deslizar a la izquierda', transitionSlideUp: 'Deslizar arriba', transitionZoom: 'Mezcla con zoom', transitionDuration: 'Duración de transición', transitionHint: 'La transición se reproduce al inicio de este clip.', transitionNeedsClip: 'Coloca este clip justo después de otro clip.', selectClipForTransition: 'Selecciona un clip de vídeo para añadir una transición',
  language: 'Idioma', appTitle: 'LumaCut — Editor de vídeo', untitledProject: 'Proyecto sin título', export: 'Exportar', exporting: 'Exportando…', media: 'Medios', audio: 'Audio', text: 'Texto', stickers: 'Stickers', effects: 'Efectos', captions: 'Subtítulos', myLibrary: 'Mi biblioteca', importMedia: 'Importar medios', inProject: 'En el proyecto', yourFile: 'Tu archivo', sample: 'Muestra', detachedDone: 'Audio separado — edición independiente', detachAudio: 'Separar audio del vídeo', dropVideo: 'Arrastra un vídeo aquí', addText: 'Añadir texto', quickStyles: 'Estilos rápidos', heading: 'Título', captionPreset: 'Subtítulo', textLayers: 'Capas de texto', importAudio: 'Importar audio', audioInProject: 'Audio del proyecto', readyTimeline: 'Listo para editar en la línea de tiempo', clickChooseAudio: 'Haz clic para elegir audio', audioTip: 'Selecciona un clip de audio, arrástralo o usa las tijeras para dividirlo', recordAudio: 'Grabar audio', stopRecording: 'Detener grabación', captionPlaceholder: 'Escribe un subtítulo…', addAtPlayhead: 'Añadir en el cabezal', importSrt: 'Importar SRT', captionsInProject: 'Subtítulos del proyecto', noCaptions: 'Aún no hay subtítulos', searchStickers: 'Buscar stickers…', noStickers: 'No se encontraron stickers', stickerCredit: 'Stickers gratis de OpenMoji · CC BY-SA 4.0', fit: 'Ajustar', animation: 'Animación', format: 'Formato', font: 'Fuente', size: 'Tamaño', rotate: 'Rotación', opacity: 'Opacidad', position: 'Posición', horizontal: 'Horizontal', vertical: 'Vertical', displayTime: 'Tiempo de visualización', start: 'Inicio', duration: 'Duración', seconds: 'segundos', deleteSticker: 'Eliminar sticker', editCaption: 'Editar subtítulo', deleteCaption: 'Eliminar subtítulo', style: 'Estilo', editText: 'Editar texto', deleteText: 'Eliminar texto', video: 'Vídeo', adjust: 'Ajustar', basic: 'Básico', stabilize: 'Estabilizar', speed: 'Velocidad', volume: 'Volumen', colorAdjust: 'Ajuste de color', brightness: 'Brillo', contrast: 'Contraste', saturation: 'Saturación', reset: 'Restablecer ajustes', mainVideo: 'Vídeo principal', trackVideo: 'Vídeo', trackText: 'Texto', trackSticker: 'Sticker', trackCaption: 'Subtítulo', trackAudio: 'Audio', splitClip: 'Dividir clip (Ctrl+B)', deleteItem: 'Eliminar (Delete)', openStickers: 'Abrir biblioteca de stickers', zoomOut: 'Alejar línea de tiempo', zoomHelp: 'Arrastra a la izquierda para alejar y a la derecha para acercar', zoomPercent: 'Porcentaje de zoom', zoomIn: 'Acercar línea de tiempo', trimStart: 'Arrastra para recortar el inicio', resizeDuration: 'Arrastra para cambiar la duración', addTrack: 'Añadir pista de {track}', deleteTrack: 'Eliminar pista de {track}', dropTitle: 'Suelta el vídeo aquí', dropDescription: 'El archivo se añadirá al proyecto', film: 'Película', lightLeak: 'Fuga de luz', blur: 'Desenfoque', grain: 'Grano', soft: 'Suave',
  noAudioFile: 'Sin archivo de audio', clip: 'Clip', zoomChanged: 'Zoom de la línea de tiempo: {zoom}%', splitHint: 'Mueve el cabezal dentro de {item} antes de dividir', splitDone: '{item} dividido', selectVideoFile: 'Selecciona un archivo de vídeo', importedVideo: 'Vídeo importado', importVideoFirst: 'Importa primero un vídeo', alreadyDetached: 'El audio ya está separado', sourceAudio: '{name} — audio del vídeo', audioSuffix: '{name} (audio)', detachedAudio: 'Audio separado del vídeo', selectAudioFile: 'Selecciona un archivo de audio', importedAudio: 'Audio añadido a la línea de tiempo', recordingUnsupported: 'Este dispositivo no admite grabación de audio', noRecordingData: 'No se capturó audio del micrófono', recordingLabel: 'Grabación {time}', recordedAudio: 'Se grabaron {duration} segundos de audio', recordingError: 'Ocurrió un error durante la grabación', recordingNow: 'Grabando… haz clic de nuevo para detener', microphoneDenied: 'Micrófono no disponible. Permite el acceso al micrófono', deleted: '{item} eliminado', newText: 'Texto nuevo', added: '{item} añadido', invalidSrt: 'No se encontraron subtítulos válidos en el archivo SRT', srtImported: 'Se importaron {count} subtítulos', srtReadFailed: 'No se pudo leer el archivo de subtítulos', moved: '{item} movido', clipStartAdjusted: 'Inicio del clip ajustado', clipDurationAdjusted: 'Duración del clip ajustada', minimumTrack: 'Se necesita al menos una pista de cada tipo', exportFirst: 'Importa un vídeo antes de exportar', preparingVideo: 'Preparando vídeo…', exportSuccess: 'Vídeo exportado correctamente', exportFailed: 'Error al exportar. Prueba con un vídeo más corto',
}

const hi: Dictionary = {
  animationNone: 'कोई नहीं', fadeIn: 'फ़ेड इन', fadeOut: 'फ़ेड आउट', zoomInAnimation: 'ज़ूम इन', slideUp: 'ऊपर स्लाइड', slideLeft: 'बाएँ स्लाइड', animationDuration: 'एनीमेशन अवधि', animationHint: 'एनीमेशन देखने के लिए चलाएँ या प्लेहेड खिसकाएँ।', selectClipForAnimation: 'एनीमेशन के लिए वीडियो क्लिप चुनें',
  transition: 'ट्रांज़िशन', transitionNone: 'कोई नहीं', crossfade: 'क्रॉसफ़ेड', fadeBlack: 'काले से फ़ेड', transitionSlideLeft: 'बाएँ स्लाइड', transitionSlideUp: 'ऊपर स्लाइड', transitionZoom: 'ज़ूम ब्लेंड', transitionDuration: 'ट्रांज़िशन अवधि', transitionHint: 'ट्रांज़िशन इस क्लिप की शुरुआत में चलेगा।', transitionNeedsClip: 'इस क्लिप को पिछले क्लिप के ठीक बाद रखें।', selectClipForTransition: 'ट्रांज़िशन जोड़ने के लिए वीडियो क्लिप चुनें',
  language: 'भाषा', appTitle: 'LumaCut — वीडियो संपादक', untitledProject: 'बिना नाम का प्रोजेक्ट', export: 'निर्यात', exporting: 'निर्यात हो रहा है…', media: 'मीडिया', audio: 'ऑडियो', text: 'टेक्स्ट', stickers: 'स्टिकर', effects: 'इफ़ेक्ट', captions: 'कैप्शन', myLibrary: 'मेरी लाइब्रेरी', importMedia: 'मीडिया आयात करें', inProject: 'प्रोजेक्ट में', yourFile: 'आपकी फ़ाइल', sample: 'नमूना', detachedDone: 'ऑडियो अलग किया गया — स्वतंत्र रूप से संपादित करें', detachAudio: 'वीडियो से ऑडियो अलग करें', dropVideo: 'वीडियो यहाँ खींचकर छोड़ें', addText: 'टेक्स्ट जोड़ें', quickStyles: 'त्वरित स्टाइल', heading: 'शीर्षक', captionPreset: 'कैप्शन', textLayers: 'टेक्स्ट लेयर', importAudio: 'ऑडियो आयात करें', audioInProject: 'प्रोजेक्ट का ऑडियो', readyTimeline: 'टाइमलाइन में संपादन के लिए तैयार', clickChooseAudio: 'ऑडियो चुनने के लिए क्लिक करें', audioTip: 'नीचे ऑडियो क्लिप चुनें, फिर उसे खींचें या कैंची से बाँटें', recordAudio: 'ऑडियो रिकॉर्ड करें', stopRecording: 'रिकॉर्डिंग रोकें', captionPlaceholder: 'कैप्शन लिखें…', addAtPlayhead: 'प्लेहेड पर जोड़ें', importSrt: 'SRT आयात करें', captionsInProject: 'प्रोजेक्ट के कैप्शन', noCaptions: 'अभी कोई कैप्शन नहीं', searchStickers: 'स्टिकर खोजें…', noStickers: 'कोई स्टिकर नहीं मिला', stickerCredit: 'OpenMoji के मुफ़्त स्टिकर · CC BY-SA 4.0', fit: 'फ़िट', animation: 'एनीमेशन', format: 'फ़ॉर्मैट', font: 'फ़ॉन्ट', size: 'आकार', rotate: 'घुमाएँ', opacity: 'अपारदर्शिता', position: 'स्थिति', horizontal: 'क्षैतिज', vertical: 'लंबवत', displayTime: 'दिखाने का समय', start: 'शुरुआत', duration: 'अवधि', seconds: 'सेकंड', deleteSticker: 'स्टिकर हटाएँ', editCaption: 'कैप्शन संपादित करें', deleteCaption: 'कैप्शन हटाएँ', style: 'स्टाइल', editText: 'टेक्स्ट संपादित करें', deleteText: 'टेक्स्ट हटाएँ', video: 'वीडियो', adjust: 'समायोजन', basic: 'मूल', stabilize: 'स्थिर करें', speed: 'गति', volume: 'आवाज़', colorAdjust: 'रंग समायोजन', brightness: 'चमक', contrast: 'कॉन्ट्रास्ट', saturation: 'संतृप्ति', reset: 'समायोजन रीसेट करें', mainVideo: 'मुख्य वीडियो', trackVideo: 'वीडियो', trackText: 'टेक्स्ट', trackSticker: 'स्टिकर', trackCaption: 'कैप्शन', trackAudio: 'ऑडियो', splitClip: 'क्लिप बाँटें (Ctrl+B)', deleteItem: 'हटाएँ (Delete)', openStickers: 'स्टिकर लाइब्रेरी खोलें', zoomOut: 'टाइमलाइन छोटा करें', zoomHelp: 'छोटा करने के लिए बाएँ और बड़ा करने के लिए दाएँ खींचें', zoomPercent: 'टाइमलाइन ज़ूम प्रतिशत', zoomIn: 'टाइमलाइन बड़ा करें', trimStart: 'शुरुआत ट्रिम करने के लिए खींचें', resizeDuration: 'अवधि बदलने के लिए खींचें', addTrack: '{track} ट्रैक जोड़ें', deleteTrack: '{track} ट्रैक हटाएँ', dropTitle: 'वीडियो यहाँ छोड़ें', dropDescription: 'फ़ाइल प्रोजेक्ट में जुड़ जाएगी', film: 'फ़िल्म', lightLeak: 'लाइट लीक', blur: 'धुंधला', grain: 'ग्रेन', soft: 'सॉफ्ट',
  noAudioFile: 'कोई ऑडियो फ़ाइल नहीं', clip: 'क्लिप', zoomChanged: 'टाइमलाइन ज़ूम {zoom}%', splitHint: 'बाँटने से पहले प्लेहेड को {item} के अंदर ले जाएँ', splitDone: '{item} बाँटा गया', selectVideoFile: 'वीडियो फ़ाइल चुनें', importedVideo: 'वीडियो आयात हुआ', importVideoFirst: 'पहले वीडियो आयात करें', alreadyDetached: 'ऑडियो पहले से अलग है', sourceAudio: '{name} — वीडियो का ऑडियो', audioSuffix: '{name} (ऑडियो)', detachedAudio: 'वीडियो से ऑडियो अलग किया गया', selectAudioFile: 'ऑडियो फ़ाइल चुनें', importedAudio: 'ऑडियो टाइमलाइन में जोड़ा गया', recordingUnsupported: 'यह डिवाइस ऑडियो रिकॉर्डिंग का समर्थन नहीं करता', noRecordingData: 'माइक्रोफ़ोन ऑडियो रिकॉर्ड नहीं हुआ', recordingLabel: 'रिकॉर्डिंग {time}', recordedAudio: '{duration} सेकंड ऑडियो रिकॉर्ड हुआ', recordingError: 'रिकॉर्डिंग के दौरान त्रुटि हुई', recordingNow: 'रिकॉर्डिंग… रोकने के लिए फिर क्लिक करें', microphoneDenied: 'माइक्रोफ़ोन उपलब्ध नहीं। अनुमति दें', deleted: '{item} हटाया गया', newText: 'नया टेक्स्ट', added: '{item} जोड़ा गया', invalidSrt: 'SRT फ़ाइल में मान्य कैप्शन नहीं मिले', srtImported: '{count} कैप्शन आयात हुए', srtReadFailed: 'कैप्शन फ़ाइल पढ़ी नहीं जा सकी', moved: '{item} खिसकाया गया', clipStartAdjusted: 'क्लिप की शुरुआत बदली गई', clipDurationAdjusted: 'क्लिप की अवधि बदली गई', minimumTrack: 'हर प्रकार का कम से कम एक ट्रैक चाहिए', exportFirst: 'निर्यात से पहले वीडियो आयात करें', preparingVideo: 'वीडियो तैयार हो रहा है…', exportSuccess: 'वीडियो सफलतापूर्वक निर्यात हुआ', exportFailed: 'निर्यात विफल। छोटा वीडियो आज़माएँ',
}

const fr: Dictionary = {
  animationNone: 'Aucune', fadeIn: 'Fondu entrant', fadeOut: 'Fondu sortant', zoomInAnimation: 'Zoom avant', slideUp: 'Glisser vers le haut', slideLeft: 'Glisser à gauche', animationDuration: 'Durée de l’animation', animationHint: 'Lancez la lecture ou déplacez la tête de lecture pour prévisualiser.', selectClipForAnimation: 'Sélectionnez un clip vidéo à animer',
  transition: 'Transition', transitionNone: 'Aucune', crossfade: 'Fondu enchaîné', fadeBlack: 'Fondu au noir', transitionSlideLeft: 'Glisser à gauche', transitionSlideUp: 'Glisser vers le haut', transitionZoom: 'Fusion zoom', transitionDuration: 'Durée de transition', transitionHint: 'La transition se joue au début de ce clip.', transitionNeedsClip: 'Placez ce clip juste après un autre clip.', selectClipForTransition: 'Sélectionnez un clip vidéo pour ajouter une transition',
  language: 'Langue', appTitle: 'LumaCut — Éditeur vidéo', untitledProject: 'Projet sans titre', export: 'Exporter', exporting: 'Exportation…', media: 'Médias', audio: 'Audio', text: 'Texte', stickers: 'Stickers', effects: 'Effets', captions: 'Sous-titres', myLibrary: 'Ma bibliothèque', importMedia: 'Importer un média', inProject: 'Dans le projet', yourFile: 'Votre fichier', sample: 'Exemple', detachedDone: 'Audio détaché — modification indépendante', detachAudio: 'Détacher l’audio de la vidéo', dropVideo: 'Glissez une vidéo ici', addText: 'Ajouter du texte', quickStyles: 'Styles rapides', heading: 'Titre', captionPreset: 'Sous-titre', textLayers: 'Calques de texte', importAudio: 'Importer un audio', audioInProject: 'Audio du projet', readyTimeline: 'Prêt à modifier dans la timeline', clickChooseAudio: 'Cliquez pour choisir un audio', audioTip: 'Sélectionnez un clip audio, déplacez-le ou utilisez les ciseaux pour le couper', recordAudio: 'Enregistrer l’audio', stopRecording: 'Arrêter l’enregistrement', captionPlaceholder: 'Saisissez un sous-titre…', addAtPlayhead: 'Ajouter à la tête de lecture', importSrt: 'Importer un SRT', captionsInProject: 'Sous-titres du projet', noCaptions: 'Aucun sous-titre', searchStickers: 'Rechercher des stickers…', noStickers: 'Aucun sticker trouvé', stickerCredit: 'Stickers gratuits par OpenMoji · CC BY-SA 4.0', fit: 'Ajuster', animation: 'Animation', format: 'Format', font: 'Police', size: 'Taille', rotate: 'Rotation', opacity: 'Opacité', position: 'Position', horizontal: 'Horizontal', vertical: 'Vertical', displayTime: 'Temps d’affichage', start: 'Début', duration: 'Durée', seconds: 'secondes', deleteSticker: 'Supprimer le sticker', editCaption: 'Modifier le sous-titre', deleteCaption: 'Supprimer le sous-titre', style: 'Style', editText: 'Modifier le texte', deleteText: 'Supprimer le texte', video: 'Vidéo', adjust: 'Ajuster', basic: 'Basique', stabilize: 'Stabiliser', speed: 'Vitesse', volume: 'Volume', colorAdjust: 'Réglage des couleurs', brightness: 'Luminosité', contrast: 'Contraste', saturation: 'Saturation', reset: 'Réinitialiser les réglages', mainVideo: 'Vidéo principale', trackVideo: 'Vidéo', trackText: 'Texte', trackSticker: 'Sticker', trackCaption: 'Sous-titre', trackAudio: 'Audio', splitClip: 'Scinder le clip (Ctrl+B)', deleteItem: 'Supprimer (Delete)', openStickers: 'Ouvrir les stickers', zoomOut: 'Réduire la timeline', zoomHelp: 'Glissez à gauche pour réduire, à droite pour agrandir', zoomPercent: 'Pourcentage de zoom', zoomIn: 'Agrandir la timeline', trimStart: 'Glissez pour rogner le début', resizeDuration: 'Glissez pour modifier la durée', addTrack: 'Ajouter une piste {track}', deleteTrack: 'Supprimer la piste {track}', dropTitle: 'Déposez la vidéo ici', dropDescription: 'Le fichier sera ajouté au projet', film: 'Film', lightLeak: 'Fuite de lumière', blur: 'Flou', grain: 'Grain', soft: 'Doux',
  noAudioFile: 'Aucun fichier audio', clip: 'Clip', zoomChanged: 'Zoom de la timeline : {zoom} %', splitHint: 'Placez la tête de lecture dans {item} avant de scinder', splitDone: '{item} scindé', selectVideoFile: 'Sélectionnez un fichier vidéo', importedVideo: 'Vidéo importée', importVideoFirst: 'Importez d’abord une vidéo', alreadyDetached: 'L’audio est déjà détaché', sourceAudio: '{name} — audio de la vidéo', audioSuffix: '{name} (audio)', detachedAudio: 'Audio détaché de la vidéo', selectAudioFile: 'Sélectionnez un fichier audio', importedAudio: 'Audio ajouté à la timeline', recordingUnsupported: 'L’enregistrement audio n’est pas pris en charge sur cet appareil', noRecordingData: 'Aucun son du microphone n’a été capturé', recordingLabel: 'Enregistrement {time}', recordedAudio: '{duration} secondes d’audio enregistrées', recordingError: 'Une erreur est survenue pendant l’enregistrement', recordingNow: 'Enregistrement… cliquez à nouveau pour arrêter', microphoneDenied: 'Microphone indisponible. Autorisez son accès', deleted: '{item} supprimé', newText: 'Nouveau texte', added: '{item} ajouté', invalidSrt: 'Aucun sous-titre valide trouvé dans le fichier SRT', srtImported: '{count} sous-titres importés', srtReadFailed: 'Impossible de lire le fichier de sous-titres', moved: '{item} déplacé', clipStartAdjusted: 'Début du clip ajusté', clipDurationAdjusted: 'Durée du clip ajustée', minimumTrack: 'Au moins une piste de chaque type est requise', exportFirst: 'Importez une vidéo avant l’exportation', preparingVideo: 'Préparation de la vidéo…', exportSuccess: 'Vidéo exportée avec succès', exportFailed: 'Échec de l’exportation. Essayez une vidéo plus courte',
}

const messages: Record<LanguageCode, Dictionary> = { en, th, ru, zh, ja, es, hi, fr }

export const translate = (language: LanguageCode, key: MessageKey, variables: Record<string, string | number> = {}) => {
  let value = messages[language][key] ?? en[key]
  Object.entries(variables).forEach(([name, replacement]) => { value = value.replaceAll(`{${name}}`, String(replacement)) })
  return value
}
